name: Update Deployment Link

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  update_deployment_link:
    runs-on: ubuntu-latest

    steps:
      - name: Update Deployments Section
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: update_deployments
          client-payload: '{"url": "https://oswebsiteg8set3.onrender.com"}'  # Replace with your Render deployment URL
